version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: dugite
    versions:
    - 1.100.0
    - 1.101.0
    - 1.102.0
    - 1.96.0
    - 1.97.0
    - 1.98.0
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: electron-builder
    versions:
    - 22.9.1
  - dependency-name: electron-updater
    versions:
    - 4.3.5
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
